# -*- coding: utf-8 -*-
"""ProjectPitch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11sA-rPDjeJYiB5eI_tAseH42HxqTSsd4
"""

# Install Chrome, ChromeDriver, and Selenium
!apt-get update
!apt install -y chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin
!pip install selenium

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from bs4 import BeautifulSoup
import pandas as pd
import time

# Setup headless Chrome for Colab
chrome_options = Options()
chrome_options.add_argument("--headless")
chrome_options.add_argument("--no-sandbox")
chrome_options.add_argument("--disable-dev-shm-usage")

driver = webdriver.Chrome(options=chrome_options)

# Load the page
url = "https://www.counterpointresearch.com/insights/us-smartphone-market-share/"
driver.get(url)
time.sleep(5)  # give time for JavaScript to load

# Parse the rendered HTML
soup = BeautifulSoup(driver.page_source, 'html.parser')
tables = soup.find_all('table')

apple_samsung_tables = []

# Search for relevant data
for table in tables:
    rows = table.find_all('tr')
    headers = [th.text.strip() for th in rows[0].find_all(['th', 'td'])]

    if 'Brands' not in headers[0] or len(headers) < 3:
        continue

    data = []
    for row in rows[1:]:
        cells = [td.text.strip() for td in row.find_all('td')]
        if not cells:
            continue
        if cells[0] in ['Apple', 'Samsung']:
            data.append([cells[0]] + [cell.replace('%','') for cell in cells[1:]])


    if data:
        df     = pd.DataFrame(data, columns=headers)
        df.set_index('Brands', inplace=True)
        df = df.transpose()
        df.reset_index(inplace=True)
        df.rename(columns={'index': 'Quarter'}, inplace=True)
        apple_samsung_tables.append(df)

driver.quit()

# Combine and show final data
final_df = pd.concat(apple_samsung_tables).drop_duplicates(subset='Quarter').reset_index(drop=True)
final_df.columns.name = None
final_df[['Apple', 'Samsung']] = final_df[['Apple', 'Samsung']].apply(pd.to_numeric)
print("Apple and Samsung Market Share Data:")
print(final_df)